### ISSUE TITLE
cannot install at all

### ISSUE THREAD

**Issue by WrRaThY** [metaplex/js#37]
I get the following error (and we don't even use husky).
`npm install @metaplex/js` was executed from the root directory (the one with .git), so I don't think that this error refers to out `.git` even?

### from gitbash (part of git for windows)
wooha@Asus-ROG-Strix MINGW64 /c/_work/_serious/Slothana/sloth-combiner (master)
$ npm install @metaplex/js
npm ERR! code 1
npm ERR! path C:\_work\sloth-combiner\node_modules\@metaplex\js
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install
npm ERR! .git can't be found (see https://git.io/Jc3F9)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wooha\AppData\Local\npm-cache\_logs\2021-10-16T21_48_50_048Z-debug.log

### from WSL (Ubuntu)
npm install @metaplex/js
npm ERR! code 1
npm ERR! path /mnt/c/_work/sloth-combiner/node_modules/@metaplex/js
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! .git can't be found (see https://git.io/Jc3F9)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wooha/.npm/_logs/2021-10-16T22_12_54_494Z-debug.log

**Comment by oboxodo** [comment]
And I tried installing it in a blank new project and it didn't work. 

```
 pepe % yarn add @metaplex/js
yarn add v1.22.15
[1/4] 🔍  Resolving packages...
warning @metaplex/js > @solana/web3.js > rpc-websockets > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
warning @metaplex/js > @solana/web3.js > jayson > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[4/4] ⠄ @metaplex/js
[-/4] ⠄ waiting...
[-/4] ⠄ waiting...
error /Users/oboxodo/repos/nft1981/pepe/node_modules/@metaplex/js: Command failed.
Exit code: 1
Command: husky install
Arguments:
Directory: /Users/oboxodo/repos/nft1981/pepe/node_modules/@metaplex/js
```

@m-sebastiyan any clue about this?

**Comment by WrRaThY** [comment]
what worked for me (as a workaround) is:
-  clone the project locally
- build  it locally
- `npm link` it to your project

**Comment by m-sebastiyan** [comment]
Hello, thanks for creating the issue. 

Fixed in 2.0.1 (#38), please try again.

**Comment by oboxodo** [comment]
@m-sebastiyan That solved it for me. Thanks! I think this ticket could be closed.

**Comment by zkhalapyan** [comment]
Is there a way to do this without linking locally? Development is harder without relying on NPM to fetch the right version.

**Comment by aheckmann** [comment]
thanks for the heads up @zkhalapyan . opened a new issue #135

**Comment by zkhalapyan** [comment]
@aheckmann seems like the blame commit is here: https://github.com/metaplex-foundation/js/commit/292d5c7c2c54a98236a690c160b6ca2a4d99aaf3

Should just revert `postinstall` to `prepare`?

**Comment by aheckmann** [comment]
[good call](https://github.com/typicode/husky#usage). will PR that

**Comment by calebporzio** [comment]
Yeah, #127 introduced a regression for this problem.

Until this is fixed in core, you can temporarily fix it by running: `npm install @metaplex/js --ignore-scripts` to skip the "husky" dependancy
