### ISSUE TITLE
Support winning config types that are not "FullRightsTransfer"?

### ISSUE THREAD

**Issue by Findiglay** [metaplex/js#71]
I'm trying to use the SDK to place and redeem bids on an instant sale auction where the safety deposit items `winningConfigType` is `WinningConfigType.PrintingV2`. However, because the `redeemBid` action does not handle different cases for `winningConfigType` ([unlike the storefront](https://github.com/metaplex-foundation/metaplex/blob/f28b27e9c5160567468a8ead89fe620edfb80b71/js/packages/web/src/actions/sendRedeemBid.ts#L154)), the SDK action attempts a`RedeemFullRightsTransferBid` transaction and fails with the error message "The prize you are attempting to claim needs to be claimed from a different endpoint than this one".
  
 Is this a currently known limitation with the SDK action or should I not be using `WinningConfigType.PrintingV2` now?

**Comment by kurpav** [comment]
Hi @Findiglay,
It's a known limitation, for now, we'll work on the other types soon.

**Comment by Findiglay** [comment]
@kurpav would I be able to open a PR to support PrintingV2? I think I might be able to put this together based on the storefront codebase.

**Comment by Findiglay** [comment]
I'll close issue for now then @kurpav

**Comment by kurpav** [comment]
@Findiglay https://github.com/metaplex/js/pull/91
